CREATE TABLE IF NOT EXISTS positions (
    id VARCHAR(150) PRIMARY KEY DEFAULT REPLACE(uuid_generate_v4()::text, '-',''),
    name VARCHAR(100) UNIQUE NOT NULL,
    department_id VARCHAR(150) NOT NULL,
    CONSTRAINT FK_POSITION_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (id) ON UPDATE NO ACTION ON DELETE CASCADE
);