CREATE TABLE IF NOT EXISTS employees (
    id VARCHAR(150) PRIMARY KEY DEFAULT REPLACE(uuid_generate_v4()::text, '-',''),
    name VARCHAR(150) UNIQUE NOT NULL,
    salary DECIMAL(7,2) NOT NULL DEFAULT 0.00,
    entry_date DATE NOT NULL,
    departure_date DATE,
    position_id VARCHAR(150) NOT NULL,
    CONSTRAINT FK_POSITION_EMPLOYEE FOREIGN KEY (position_id) REFERENCES positions (id) ON UPDATE NO ACTION ON DELETE CASCADE
);